In [22]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import sklearn as sk

# Use this instead
df = pd.read_csv('The FINAL Dataset.csv')


from sklearn import linear_model

df =  df.dropna()

df['2019 raw GDP'] = df['2019 raw GDP'].astype('float64')
df['percent change 2020'] = df['percent change 2020'].astype('float64')
df['cases'] = df['cases'].astype('int32')
df['deaths'] = df['deaths'].astype('int32')

from sklearn.preprocessing import StandardScaler
  
#object= StandardScaler()
  
#df['cases'] = object.fit_transform(df['cases'].values.reshape(-1, 1)) 
#df['deaths'] = object.fit_transform(df['deaths'].values.reshape(-1, 1)) 
#df['2020 population'] = object.fit_transform(df['2020 population'].values.reshape(-1, 1))
#df['2019 raw GDP'] = object.fit_transform(df['2019 raw GDP'].values.reshape(-1, 1)) 
#df['percent change 2020'] = object.fit_transform(df['percent change 2020'].values.reshape(-1, 1)) 

X = df.copy().drop(columns = ['percent change 2020', 'state', 'county'])
y = df['percent change 2020']
display(df)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = sk.model_selection.train_test_split(X, y, test_size=0.2, random_state= 25)


regr = linear_model.LinearRegression()
regr.fit(x_train, y_train)

print(regr.coef_)


predictions = regr.predict(x_test)

from sklearn.metrics import classification_report
#print(classification_report(y_test, predictions))

from sklearn.metrics import mean_squared_error
print("Mean Squared Error: %.7f" % mean_squared_error(y_test, predictions))

from sklearn.metrics import r2_score
r2_score(y_test, predictions)

,county,state,cases,deaths,2020 population,2019 raw GDP,percent change 2020
0,Autauga,Alabama,4190,48,58877.0,1540762.0,-1.3
1,Baldwin,Alabama,13601,161,233140.0,7134734.0,-2.1
2,Barbour,Alabama,1514,32,25180.0,729105.0,-5.8
3,Bibb,Alabama,1834,46,22223.0,380453.0,2.1
4,Blount,Alabama,4641,63,59081.0,932215.0,-5.4
...,...,...,...,...,...,...,...
3240,Sweetwater,Wyoming,2966,16,42158.0,3677972.0,-10.9
3241,Teton,Wyoming,2138,4,23347.0,2268742.0,-4.1
3242,Uinta,Wyoming,1558,7,20441.0,881052.0,-10.3
3243,Washakie,Wyoming,780,19,7658.0,349686.0,-3.7
3244,Weston,Wyoming,476,2,6809.0,322576.0,-3.1

,county,state,cases,deaths,2020 population,2019 raw GDP,percent change 2020
0,Autauga,Alabama,4190,48,58877.0,1540762.0,-1.3
1,Baldwin,Alabama,13601,161,233140.0,7134734.0,-2.1
2,Barbour,Alabama,1514,32,25180.0,729105.0,-5.8
3,Bibb,Alabama,1834,46,22223.0,380453.0,2.1
4,Blount,Alabama,4641,63,59081.0,932215.0,-5.4
...,...,...,...,...,...,...,...
3240,Sweetwater,Wyoming,2966,16,42158.0,3677972.0,-10.9
3241,Teton,Wyoming,2138,4,23347.0,2268742.0,-4.1
3242,Uinta,Wyoming,1558,7,20441.0,881052.0,-10.3
3243,Washakie,Wyoming,780,19,7658.0,349686.0,-3.7
3244,Weston,Wyoming,476,2,6809.0,322576.0,-3.1

[ 8.68811618e-05 -1.49581719e-03 -9.75807577e-06  5.31720328e-08]
Mean Squared Error: 52.1303994

0.006909556717841769